### ISSUE TITLE
🗨️ 

### ISSUE THREAD

**Issue by pastaChaeng** [pastaChaeng/Anime-Watchlist#3]
wala na 'to?  @emjay03 
![image](https://github.com/pastaChaeng/Anime-Watchlist/assets/123816211/e888842a-d2d3-4a6d-8861-4f6a2bdd9446)

**Comment by emjay03** [comment]
@pastaChaeng oo wla nyn bali yung bago kong push ayon n yung latest working na search both airing and banner may slider yn

**Comment by pastaChaeng** [comment]
@emjay03 sige boss
